require('dotenv').config();

function mapPresence(val) {
    const mapping = {
        typing: 'composing',
        online: 'available',
        recording: 'recording',
        paused: 'paused',
        offline: 'unavailable'
    };
    return mapping[val?.toLowerCase()?.trim()] || 'paused';
}

module.exports = {
    prefixes: process.env.PREFIX
        ? process.env.PREFIX.split('.').map(p => p.trim())
        : ['.'],

    NUMBER: process.env.YOUR_NUMBER || '255674479072',
    MODE: (process.env.MODE || 'private').toLowerCase().trim(),
    WARN_LIMIT: process.env.WARNINGS || '3',
    ON: process.env.YOUR_NAME || 'Jamal Said😈',
    ANTICALL: process.env.ANTICALL || 'off',
    ADM: process.env.ANTIDELETE || 'off',
    AR: process.env.AUTO_REACTION || 'off',

    AUTO_VIEW_STATUS: process.env.AUTO_READ_STATUS === 'on',
    AUTO_LIKE: process.env.AUTO_LIKE === 'off',
    AUTO_READ_MESSAGES: process.env.AUTO_READ_DM === 'off',
    HEROKU_API_KEY: process.env.HEROKU_API_KEY,
    HEROKU_APP_NAME: process.env.HEROKU_APP_NAME,
    sessionBase64: process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSUhtZndFWCt3eTVhUVR5ZGw4dE11cUp1UW9jaFJ3d2F4QjRvb05CNWkwRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiV0JhZjUwOXJQQlBtZDVkQWdHSk1mUkMxQWZZR1FWOEFBYmkrZDRFYmRoZz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJhRm81WndEbWhWeWs2Z2w4RDhZSUhvYmZEZFcwRDkvd3YxUWFRSWNCcTJNPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJoeThEN3hMNEZvVnZzU1lCTlBGQ05FQUNFKzVEZkRDb2RteXdtNEt5ZmswPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjhQb2U0dURzeEU5T3dYeUVqN0VIendPK3VHc0tKRmdkSTJnTDZPczRMRm89In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ii9ic29MZVl2NXQ4aGhOaTljSFkwRVk4UXZqRjBETVVlbHpmbFZlZ25HVk09In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiY1BRc0lDS0tmMDlIUGVwSVJDdnRjODAwazN6RFJnTGdpZTFzbDB2MkxXdz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUkVQNzRIZThDeWFlLysrbWk3RXNYMTQ4d3E5RDdYNFJRSDdyWDNSTDBTMD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImxVNFUvUVdaRE90VitSZjdaK2swc0l1QTNUV0F2d2h6d3BpZVc0TmFuR29MVzh6dkEyZlgwNmZrUkdwUDM4VFZmNU1TK0xtOXhsV0xIVFR5SmZ6NWlnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NDUsImFkdlNlY3JldEtleSI6InpjV3pWa2dTeDY5SVBPUlJGRkVST1ZINWM4QmR6Mi85aE92azVNbEtIZlk9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjU1Njc0NDc5MDcyQHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkMzM0UxREFCMkNBMzhCMTY2RURDRDZFRDQzNDdFRDZGIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NTIxNDcwNzV9LHsia2V5Ijp7InJlbW90ZUppZCI6IjI1NTY3NDQ3OTA3MkBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI1MEU0NDVFMEUzOEJBN0QzRDc0ODMwMTBDRjQ1MzM5NiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzUyMTQ3MDc2fV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiJNOTFGWFMzQSIsIm1lIjp7ImlkIjoiMjU1Njc0NDc5MDcyOjc1QHMud2hhdHNhcHAubmV0IiwibGlkIjoiMjM5OTY4OTQ5NjY2MDI1Ojc1QGxpZCIsIm5hbWUiOiJKYW1hbCBTYWlkIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNNaVFqL01IRVBQSXZzTUdHQU1nQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJaQTR0YjVtanJtaGJESkFJY2dHWHVHc3FDckhBTzdOTFZtcTQ4YjVoQmhvPSIsImFjY291bnRTaWduYXR1cmUiOiJtd3drK05lSkNUMys2elFheGVvYTNodi8wVEZUVWVJTlc1ZE1WNzVvZmg5SjZNS3RndHNYUldNRlM2a29PZkNRSjNWQXpDVVdxUmRRRWtOK1pEMEVCUT09IiwiZGV2aWNlU2lnbmF0dXJlIjoiU25SS2d2ZGJWeU9vK0ROYnJVenhpMTZVMXhMSVFVMHVEdld6TmVscWdhNDBQNTFtWjNkT3h5U3EzN2syaEZKZVRHenVFaUNjVElOa1RlUURmb0V4Z3c9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNTU2NzQ0NzkwNzI6NzVAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCV1FPTFcrWm82NW9Xd3lRQ0hJQmw3aHJLZ3F4d0R1elMxWnF1UEcrWVFZYSJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FVSUVnPT0ifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzUyMTQ3MDczLCJsYXN0UHJvcEhhc2giOiIzZ1BVSmsiLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQVAvTSJ9',
    timezone: 'Africa/Nairobi',

    USER_LID: process.env.YOUR_LID || null,

    PRESENCE_DM: mapPresence(process.env.PRESENCE_DM || 'typing'),
    PRESENCE_GROUP: mapPresence(process.env.PRESENCE_GROUP || 'recording'),

    mapPresence
};
